import time
import os
check1 = False
def clearConsole():
    command = 'clear'
    if os.name in ('nt', 'dos'):  
        command = 'cls'
    os.system(command)
while True:
  start = input("Click enter to start ")
  clearConsole()
  time.sleep(1)
  print("September 1st, 2034")
  print("Lviv, Ukraine")
  time.sleep(3)
  print("*Alarm beeps*")
  time.sleep(3)
  print("You: *Yawn* I haven't slept very well, I should take a bath")
  print("*Takes a bath*")
  time.sleep(3)
  print("You: Time for breakfast, let's see what's new on the tv")
  print("*Turns on tv*")
  time.sleep(3)
  print("Newscast: In the last two hours attacks from Russia have been reported, the whole country is under nuclear attack alert, please go to the nearest shelter")
  time.sleep(4)
  print("(You think about calling a loved one)")
  print("a. Your mother")
  print("b. Your friend")
  print("c. Your sister")
  q1 = input("Who are you calling? ")
  clearConsole()
  if (q1 == "a"):
    print("You decided to call your mother")
    time.sleep(2)
    print("*Phone dialing*")
    time.sleep(2)
    print("You: Hello?")
    time.sleep(2)
    print("Mother: Hello")
    time.sleep(2)
    print("You: Did you watch the news?")
    time.sleep(2)
    print("Mother: Yes, What should we do?")
    time.sleep(2)
    print("You: Let's go to a shelter")
    time.sleep(2)
    print("Mother: Yes, Where do we meet?")
    print("a. Park")
    print("b. Outside mother's house")
    print("c. Store")
    q2 = input("Where do you decide to go? ")
    clearConsole()
    if (q2 == "a"):
      print("You: Let's meet at the Park")
      time.sleep(2)
      print("Mother: OK")
      time.sleep(2)
      print("You pick up your backpack and you fill it with necessary things, your backpack can only carry three things, so you decide what yo put in your backpack")
      time.sleep(5)
      print("a. Canned soup, water bottles, cellphone")
      print("b. Canned soup, lantern, shotgun")
      print("c. Water bottles, radio, gas mask")
      q3 = input("What are you taking? ")
      clearConsole()
      if (q3 == "a"):
        print("You decided to take canned soup, water bottles, cellphone")
        time.sleep(2)
        print("You start your way to the Park, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        clearConsole()
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the park with a car")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the park with a bike")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the park with the subway")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
      if (q3 == "b"):
        print("You decided to take canned soup, lantern, shotgun")
        time.sleep(2)
        print("You start your way to the Park, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the park with a car")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the park with a bike")
          time.sleep(2)
          print("You arrived to the park")
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the park with the subway")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
      if (q3 == "c"):
        print("You decided to take water bottles, radio, gas mask")
        time.sleep(2)
        print("You start your way to the Park, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the park with a car")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the park with a bike")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the park with the subway")
          time.sleep(2)
          print("You arrived to the park")
          check1 = True
    if (q2 == "b"):
      print("You: Let's meet at your house")
      time.sleep(2)
      print("Mother: OK")
      time.sleep(2)
      print("You pick up your backpack and you fill it with necessary things, your backpack can only carry three things, so you decide what yo put in your backpack")
      time.sleep(5)
      print("a. Canned soup, water bottles, cellphone")
      print("b. Canned soup, lantern, shotgun")
      print("c. Water bottles, radio, gas mask")
      q3 = input("What are you taking? ")
      clearConsole()
      if (q3 == "a"):
        print("You decided to take canned soup, water bottles, cellphone")
        time.sleep(2)
        print("You start your way to your mother's house, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        clearConsole()
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to mother's house with a car")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to mother's house with a bike")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to mother's with the subway")
          time.sleep(2)
          print("You arrived to the mother's house")
          check1 = True
      if (q3 == "b"):
        print("You decided to take canned soup, lantern, shotgun")
        time.sleep(2)
        print("You start your way to mother's, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to mother's house with a car")
          time.sleep(2)
          print("You arrived to the mother's house")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to mother's house with a bike")
          time.sleep(2)
          print("You arrived to mother's house")
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to mother's house with the subway")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
      if (q3 == "c"):
        print("You decided to take water bottles, radio, gas mask")
        time.sleep(2)
        print("You start your way to mother's house, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to mother's house with a car")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to mother's house with a bike")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to mother's house with the subway")
          time.sleep(2)
          print("You arrived to mother's house")
          check1 = True
    if (q2 == "c"):
      print("You: Let's meet at the store")
      time.sleep(2)
      print("Mother: OK")
      time.sleep(2)
      print("You pick up your backpack and you fill it with necessary things, your backpack can only carry three things, so you decide what yo put in your backpack")
      time.sleep(5)
      print("a. Canned soup, water bottles, cellphone")
      print("b. Canned soup, lantern, shotgun")
      print("c. Water bottles, radio, gas mask")
      q3 = input("What are you taking? ")
      clearConsole()
      if (q3 == "a"):
        print("You decided to take canned soup, water bottles, cellphone")
        time.sleep(2)
        print("You start your way to the store, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        clearConsole()
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the store with a car")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the store with a bike")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the store with the subway")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
      if (q3 == "b"):
        print("You decided to take canned soup, lantern, shotgun")
        time.sleep(2)
        print("You start your way to the store, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the store with a car")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the store with a bike")
          time.sleep(2)
          print("You arrived to the store")
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the store with the subway")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
      if (q3 == "c"):
        print("You decided to take water bottles, radio, gas mask")
        time.sleep(2)
        print("You start your way to the store, but it is too far to go by foot, so you decide to pick a vehicle")
        time.sleep(2)
        print("a. Car")
        print("b. Bike")
        print("c. Subway")
        q4 = input("What vehicle are you taking? ")
        if (q4 == "a"):
          print("You decided to take a car")
          time.sleep(2)
          print("You start your way to the store with a car")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
        if (q4 == "b"):
          print("You decided to take a bike")
          time.sleep(2)
          print("You start your way to the store with a bike")
          time.sleep(2)
          print("You arrived to the store")
          check1 = True
        if (q4 == "c"):
          print("You decided to take the subway")
          time.sleep(2)
          print("You start your way to the store with the subway")
          time.sleep(2)
          print("You arrived to the store")
  if (q1 == "b"):
    print("You decided to call your friend")
    time.sleep(2)
    print("*Phone dialing*")
    time.sleep(2)
    print("You: Hello?")
    time.sleep(2)
    print("Friend: Hi")
    time.sleep(2)
    print("You: Did you watch the news?")
    time.sleep(2)
    print("Friend: ...")
    time.sleep(3)
    print("*Gunfire*")
    time.sleep(3)
    print("Friend: I have to go")
    time.sleep(2)
    print("You: Wait wait wait what????")
    time.sleep(2)
    print("*Beeeeeeeeeeeeeep*")
    time.sleep(2)
    print("you listen someone screaming...")
    time.sleep(1)
    print("waatch oout waaaatch ouuutt")
    time.sleep(2)
    print("a rooockeeet")
    time.sleep(2)
    print("you see a a little boy")
  if (q1 == "c"):
    print("You decided to call your sister")
    time.sleep(2)
    print("*Phone dialing*")
    time.sleep(2)
    print("You: Hi?")
    time.sleep(2)
    print("Sister: Hi, what happens?")
    time.sleep(2)
    print("You: I saw on the news that Russia is attacking the country ")
    time.sleep(2)
    print("You: And what should we do?")
    time.sleep(2)
    print("Sister: Let's leave the country!")
    time.sleep(2)
    print("You: How are we doing that?!")
    time.sleep(2)
    print("Sister: You're right, all highways and flights are blocked")
    time.sleep(2)
    print("You: By now we should find provisions and hide, Russian troops are coming")
    time.sleep(2)
    print("You think on a place to meet")
    time.sleep(2)
    print("a. Your house")
    print("b. sister's house")
    print("c. Mall")
    q2 = input("Where do you choose to meet?")
    clearConsole()
    if (q2 == "a"):
      print("You decide to meet your sister at your house")
      print("You: Let's meet at my house")
      print("Sister: OK")
      print("You start to wait the arrival of your sister to your house, but you need provisions, then you remember there is a convenience store in the next square")
      print("a. Don't go")
      print("b. Go")
      q3 = input("What do you decide?")
      clearConsole()
      if (q3 =="a"):
        print("You decided not to go, too risky")
      if (q3 == "b"):
        print("You decided to go")
    if (q2 == "b"):
      print("You decide to meet your sister at your sister's house")
      print("You: Let's meet at your house")
      print("Sister: OK")
      print("You think on how are you going to travel all the way to your sister's house, it is too far")
      print("a. Car")
      print("b. Bike")
      print("c. Subway")
      q3 = input("What vehicle do you choose?")
      if (q3 == "a"):
        print("You decided to take your car")
      if (q3 == "b"):
        print("You decided to take your bike")
      if (q3 == "c"):
        print("You decided to take the subway")
    if (q2 == "c"):
      print("You decide to meet your sister at the Mall")
      print("You: Let's meet at the Mall")
      print("Sister: OK")
      print("You live near the Mall so you decide to go by foot")
      print("You finally arrive to the Mall")
      print("You enter the Mall to wait your sister, you find other people in the Mall")